name: YAML Validation

on:
  push:
    branches:
      - master  # Change this to the branch you want to monitor

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3  # Choose the Python version you want to use

    - name: Install PyYAML
      run: pip install pyyaml

    - name: Validate YAML
      run: python validate_yaml.py /c/Users/MOHAMMED ARIF/python_script_yamlvalidation/yaml_file.yaml  # Replace with the actual path to your YAML file